require('pry')

require_relative( 'models/customer')
require_relative( 'models/film')
require_relative( 'models/ticket')

Ticket.delete_all()
Film.delete_all()
Customer.delete_all()

customer1 = Customer.new({'name' => 'Bill', 'fund' => 50 })
customer1.save()
customer2 = Customer.new({'name' => 'John', 'fund' => 35 })
customer2.save()
customer3 = Customer.new({'name' => 'George', 'fund' => 75 })
customer3.save()
customer4 = Customer.new({'name' => 'Neil', 'fund' => 90 })
customer4.save()

film1 = Film.new({'title' => 'Jaws', 'price' => 7 })
film1.save()
film2 = Film.new({'title' => 'Alien', 'price' => 8 })
film2.save()
film3 = Film.new({'title' => 'Star Wars', 'price' => 5 })
film3.save()
film4 = Film.new({'title' => 'Independence Day', 'price' => 9 })
film4.save()

ticket1 = Ticket.new({'customer_id' => customer1.id, 'film_id' => film1.id })
ticket1.save()
ticket2 = Ticket.new({'customer_id' => customer1.id, 'film_id' => film2.id })
ticket2.save()
ticket3 = Ticket.new({'customer_id' => customer1.id, 'film_id' => film3.id })
ticket1.save()
ticket4 = Ticket.new({'customer_id' => customer1.id, 'film_id' => film4.id })
ticket1.save()
ticket5 = Ticket.new({'customer_id' => customer2.id, 'film_id' => film2.id })
ticket5.save()
ticket6 = Ticket.new({'customer_id' => customer2.id, 'film_id' => film4.id })
ticket6.save()
ticket7 = Ticket.new({'customer_id' => customer3.id, 'film_id' => film1.id })
ticket7.save()
ticket8 = Ticket.new({'customer_id' => customer3.id, 'film_id' => film3.id })
ticket8.save()
ticket9 = Ticket.new({'customer_id' => customer4.id, 'film_id' => film3.id })
ticket9.save()
ticket10 = Ticket.new({'customer_id' => customer4.id, 'film_id' => film4.id })
ticket10.save()
# ticket1 = Ticket.new({'customer_id' => customer1, 'film_id' => film1 })
# ticket1.save()
# ticket1 = Ticket.new({'customer_id' => customer1, 'film_id' => film1 })
# ticket1.save()

binding pry
nil